// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yU9VAeCJSoBV9J2Nsok6bvWUuOBJiT0',
    appId: '1:757591323416:web:d7ff053e186188330f646d',
    messagingSenderId: '757591323416',
    projectId: 'chat-app-e18b0',
    authDomain: 'chat-app-e18b0.firebaseapp.com',
    storageBucket: 'chat-app-e18b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmCNq0oZ85d7lK7MYmkEM_mkzNAFMw4o',
    appId: '1:757591323416:android:9aea21cac5b7556c0f646d',
    messagingSenderId: '757591323416',
    projectId: 'chat-app-e18b0',
    storageBucket: 'chat-app-e18b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQu4W5Ao23Q4gW79jyw1TL8n5AlGYMPys',
    appId: '1:757591323416:ios:2d7d102f96bd50410f646d',
    messagingSenderId: '757591323416',
    projectId: 'chat-app-e18b0',
    storageBucket: 'chat-app-e18b0.appspot.com',
    iosClientId: '757591323416-34a6b2j0cdbs95b0ueq0l6ct0k9olbr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQu4W5Ao23Q4gW79jyw1TL8n5AlGYMPys',
    appId: '1:757591323416:ios:90219ed010983d660f646d',
    messagingSenderId: '757591323416',
    projectId: 'chat-app-e18b0',
    storageBucket: 'chat-app-e18b0.appspot.com',
    iosClientId: '757591323416-pcvg8fnppv2gd0rum5tm71p86m1h5muq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
